#pragma once

// TODO: define error code for this library

enum class NET_ERROR_CODE : short
{
	NONE = 0,

	INVALID_SESSION,
	SESSION_NOT_OPENED,

	DISPATCH_ERROR,

	FAIL_SOCKET_CREATE,
	FAIL_SOCKET_LISTEN,
	FAIL_SOCKET_BIND,
	FAIL_SOCKET_ACCEPT,
	FAIL_CONNECTEX_LOAD,
	FAIL_CONNECTEX_CALL,
	FAIL_CONNECTEX_PENDIG_JOB,
	FAIL_SETSOCKOPT,

	FAIL_WSA_RECV,
	FAIL_WSA_SEND,
	FAIL_LINK_SOCKET_TO_SESSION,

	PACKET_BUFFER_FULL,
	SEND_DATA_EXCEEDED_BUFFER,

	SESSION_MAX,
};
